path.n: NAMESPACE
path.d: DESCRIPTION
dir.r: R
dir.v: vignettes
dir.t: tests
pkg_ignore:
  - gargle
  - googlesheets4
document: yes
normalize: no
inside_rmd: no
must.exist: yes
check_if_suggests_is_installed: yes
